idcops/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, include, static
from idcops import views
from idcops.list import ListModelView
from idcops.detail import DetailModelView
from idcops.edit import NewModelView, EditModelView

app_name = 'idcops'


accounts_urls = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^profile/', views.ProfileView.as_view(), name='profile'),
    url(r'^password_change/$', views.password_change, name='password_change'),
    url(r'^password_change/done/$', views.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.reset, name='password_reset_confirm'),
    url(r'^reset/done/$', views.reset_done, name='password_reset_complete'),
]


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^list/zonemap/', views.ZonemapView.as_view(), name='zonemap'),
    url(r'^(?:new/(?P<model>\w+))/$', NewModelView.as_view(), name='new'),
    url(r'^(?:list/(?P<model>\w+))/$', ListModelView.as_view(), name='list'),
    url(r'^(?:detail/(?:(?P<model>\w+)-(?P<pk>\d+)))/$', DetailModelView.as_view(), name='detail'),
    url(r'^(?:update/(?:(?P<model>\w+)-(?P<pk>\d+)))/$', EditModelView.as_view(), name='update'),
    url(r'^upload/$', views.SummernoteUploadAttachment.as_view(), name='upload'),
]


if settings.DEBUG:
    urlpatterns += static.static(settings.STATIC_URL,
                                 document_root=settings.STATIC_ROOT)
    urlpatterns += static.static(settings.MEDIA_URL,
                                 document_root=settings.MEDIA_ROOT)

idcops_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import notifications.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('idcops.urls')),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

idcops/lib/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

try:
    import chain
except:
    from itertools import chain

from django.db import models
from django.utils import formats, six, timezone

class ModelDiffMixin(object):
    """
    A model mixin that tracks model fields' values and provide useful API
    to know what fields have been changed.

    The main value is to allow simply changing the values and then saving the
    object only if it is "really changed"
    """
    def __init__(self, *args, **kwargs):
        super(ModelDiffMixin, self).__init__(*args, **kwargs)
        self.__initial = self._dict

    @property
    def diff(self):
        d1 = self.__initial
        d2 = self._dict
        diffs = [(k, (v, d2[k])) for k, v in d1.items() if v != d2[k]]
        return dict(diffs)

    @property
    def has_changed(self):
        return bool(self.diff)

    @property
    def changed_fields(self):
        return list(self.diff.keys())

    @property
    def get_d1(self):
        return self.__initial

    @property
    def get_d2(self):
        return self._dict

    @property
    def changed_field_names(self):
        data = {}
        for field_name in self.changed_fields:
            field = self._meta.get_field(field_name)
            data[field.name] = field.verbose_name
        return data

    @property
    def _dict(self):
        exclude = ['operator_id', 'creator_id', 'created', 'modified']
        opts = self._meta
        data = {}
        keys = [f.attname for f in opts.fields]
        for f in chain(opts.many_to_many):
            #if isinstance(f, models.ManyToManyField):
            if self.pk is None:
                data[f.name] = []
            else:
                data[f.name] = list(f.value_from_object(self).values_list('pk', flat=True))
        original = { k:self.__dict__.get(k) for k in keys if k not in exclude }
        data.update(**original)
        for key, value in data.items():
            if isinstance(value, timezone.datetime):
                value = formats.localize(timezone.template_localtime(value))
            data.update(**{key: value})
        return data

    def get_field_diff(self, field_name):
        """
        Returns a diff for field if it's changed and None otherwise.
        """
        return self.diff.get(field_name, None)

    def save(self, *args, **kwargs):
        """
        Saves model and set initial state.
        """
        super(ModelDiffMixin, self).save(*args, **kwargs)
        self.__initial = self._dict

    class Meta:
        abstract = True


class AbsoluteUrlMixin(object):
    def get_absolute_url(self):
        opts = self._meta
        if opts.proxy:
            opts = opts.concrete_model._meta
        return reverse_lazy(
            'admin:{}_{}_change'.format(
                opts.app_label, opts.model_name
            ), args=(self.pk,)
        )

idcops/lib/models/utils.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import hashlib
import mimetypes
import filetype


def get_file_mimetype(filepath):
    _, ext = os.path.splitext(filepath)
    kind = filetype.guess(filepath)
    if kind:
        mime = kind.mime
        ext = '.' + kind.extension
    else:
        try:
            mime = mimetypes.types_map.get(ext)
        except:
            mime = ext = None
    return (mime, ext)

idcops/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Create your views here.
from django.apps import apps
from django.views.generic import View, TemplateView
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView, PasswordChangeDoneView,
    PasswordChangeView
)
from django.template.loader import render_to_string
from django.utils.translation import ugettext as _
from django.utils.encoding import force_text
from django.utils.functional import cached_property

try:
    from django.core.urlresolvers import reverse_lazy
except:
    from django.urls import reverse_lazy

from idcops.lib.utils import shared_queryset
from idcops.mixins import BaseRequiredMixin
from idcops.models import (
    Option, Rack, Device, Online, Syslog, ContentType, Zonemap, Client
)
from idcops.forms import ZonemapNewForm


login = LoginView.as_view(template_name='accounts/login.html')

logout = LogoutView.as_view(template_name='accounts/logout.html')

password_reset = PasswordResetView.as_view(
    template_name='accounts/password_reset_form.html',
    email_template_name='accounts/password_reset_email.html',
    subject_template_name='accounts/password_reset_subject.txt',
)

password_reset_done = PasswordResetDoneView.as_view(
    template_name='accounts/password_reset_done.html'
)

reset = PasswordResetConfirmView.as_view(
    template_name='accounts/password_reset_confirm.html'
)

reset_done = PasswordResetCompleteView.as_view(
    template_name='accounts/password_reset_complete.html'
)


class PasswordChangeView(BaseRequiredMixin, PasswordChangeView):
    template_name = 'accounts/password_change_form.html'
    success_url = reverse_lazy('idcops:index')


password_change = PasswordChangeView.as_view()

password_change_done = PasswordChangeDoneView.as_view(
    template_name='accounts/password_change_done.html'
)


class SummernoteUploadAttachment(BaseRequiredMixin, View):
    def __init__(self):
        super(SummernoteUploadAttachment, self).__init__()

    def get(self, request, *args, **kwargs):
        return JsonResponse({
            'status': 'false',
            'message': _('Only POST method is allowed'),
        }, status=400)

    def post(self, request, *args, **kwargs):
        if not request.FILES.getlist('files'):
            return JsonResponse({
                'status': 'false',
                'message': _('No files were requested'),
            }, status=400)

        # remove unnecessary CSRF token, if found
        kwargs = request.POST.copy()
        kwargs.pop("csrfmiddlewaretoken", None)

        try:
            attachments = []

            for file in request.FILES.getlist('files'):

                # create instance of appropriate attachment class
                from idcops.models import Attachment
                attachment = Attachment()

                attachment.onidc = request.user.onidc
                attachment.creator = request.user
                attachment.file = file
                attachment.name = file.name

                if file.size > 1024 * 1024 * 10:
                    return JsonResponse({
                        'status': 'false',
                        'message': _('File size exceeds the limit allowed and cannot be saved'),
                    }, status=400)

                # calling save method with attachment parameters as kwargs
                attachment.save(**kwargs)
                attachments.append(attachment)

            return HttpResponse(render_to_string('document/upload_attachment.json', {
                'attachments': attachments,
            }), content_type='application/json')
        except IOError:
            return JsonResponse({
                'status': 'false',
                'message': _('Failed to save attachment'),
            }, status=500)


class IndexView(BaseRequiredMixin, TemplateView):

    template_name = 'index.html'

    def make_years(self, queryset):
        years = queryset.datetimes('created', 'month')
        if years.count() > 12:
            ranges = years[(years.count()-12):years.count()]
        else:
            ranges = years[:12]
        return ranges

    def make_device_dynamic_change(self):
        content_type = ContentType.objects.get_for_model(Device)
        logs = Syslog.objects.filter(
            onidc_id=self.onidc_id, content_type=content_type)
        data = {}
        data['categories'] = [m.strftime("%Y-%m")
                              for m in self.make_years(logs)]
        data['moveup'] = []
        data['moving'] = []
        data['movedown'] = []
        for y in self.make_years(logs):
            nlogs = logs.filter(created__year=y.year, created__month=y.month)
            moving = nlogs.filter(
                message__contains='"units"', action_flag="修改").exclude(
                content__contains='"units": [[]').count()
            data['moving'].append(moving)
            moveup = nlogs.filter(action_flag="新增").count()
            data['moveup'].append(moveup)
            cancel_movedown = nlogs.filter(action_flag="取消下架").count()
            movedown = nlogs.filter(action_flag="下架").count()
            data['movedown'].append(movedown-cancel_movedown)
        return data

    def make_rack_dynamic_change(self):
        content_type = ContentType.objects.get_for_model(Rack)
        logs = Syslog.objects.filter(
            onidc_id=self.onidc_id, content_type=content_type)
        data = {}
        data['categories'] = [m.strftime("%Y-%m")
                              for m in self.make_years(logs)]
        data['renew'] = []
        data['release'] = []
        for y in self.make_years(logs):
            nlogs = logs.filter(created__year=y.year, created__month=y.month)
            data['renew'].append(nlogs.filter(action_flag="分配机柜").count())
            data['release'].append(nlogs.filter(action_flag="释放机柜").count())
        return data

    def make_rack_statistics(self):
        data = []
        robjects = Rack.objects.filter(onidc_id=self.onidc_id, actived=True)
        keys = Option.objects.filter(
            flag__in=['Rack-Style', 'Rack-Status'],
            actived=True)
        keys = shared_queryset(keys, self.onidc_id)
        for k in keys:
            d = []
            query = {
                k.flag.split('-')[1].lower(): k
            }
            c = robjects.filter(**query).count()
            if c > 0:
                d.append(force_text(k))
                d.append(c)
            if d:
                data.append(d)
        return data

    def make_online_statistics(self):
        data = []
        dobjects = Online.objects.filter(onidc_id=self.onidc_id)
        keys = Option.objects.filter(flag__in=['Device-Style', 'Device-Tags'])
        keys = shared_queryset(keys, self.onidc_id)
        for k in keys:
            d = []
            if k.flag == 'Device-Style':
                c = dobjects.filter(style=k).count()
            else:
                c = dobjects.filter(tags__in=[k]).count()
            if c > 0:
                d.append(force_text(k))
                d.append(c)
            if d:
                data.append(d)
        return data

    def make_state_items(self):
        state_items = [
            {
                'model_name': app._meta.model_name,
                'verbose_name': app._meta.verbose_name,
                'icon': app._meta.icon,
                'icon_color': 'bg-' + app._meta.icon_color,
                'level': app._meta.level,
                'metric': app._meta.metric,
                'count': app.objects.filter(
                    onidc=self.request.user.onidc).filter(
                    **app._meta.default_filters).count(),
            } for app in apps.get_app_config('idcops').get_models() if getattr(
                app._meta,
                'dashboard')]
        return state_items

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['state_items'] = self.make_state_items()
        context['online_statistics'] = self.make_online_statistics()
        context['device_dynamic_change'] = self.make_device_dynamic_change()
        context['rack_statistics'] = self.make_rack_statistics()
        context['rack_dynamic_change'] = self.make_rack_dynamic_change()
        return context


class ProfileView(BaseRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

    # def get(self, *args, **kwargs):
        # messages.success(self.request, "accounts/profile.html")
        # return super(ProfileView, self).get(*args, **kwargs)


class ZonemapView(BaseRequiredMixin, TemplateView):

    template_name = 'zonemap/detail.html'

    @cached_property
    def get_options(self):
        options = Option.objects.filter(actived=True)
        return shared_queryset(options, self.onidc_id)

    @cached_property
    def get_zones(self):
        return self.get_options.filter(flag='Rack-Zone')

    @cached_property
    def get_zone(self):
        ''' get current zone return zone instance'''
        zone_id = self.request.GET.get('zone_id', None)
        try:
            zone = self.get_zones.get(pk=int(zone_id))
        except BaseException:
            if self.get_zones.filter(master=True).exists():
                zone = self.get_zones.filter(master=True).first()
            else:
                zone = None
        return zone

    def get_mode(self):
        action = self.request.GET.get('action', 'show')
        return action

    def get_racks(self):
        if self.get_zone:
            return Rack.objects.filter(zone_id=self.get_zone)
        return None

    def get_rack_statistics(self):
        data = []
        keys = self.get_options.filter(flag__in=['Rack-Style', 'Rack-Status'])
        ''' id, color, text, flag, description, count '''

idcops/templates/accounts/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}数据中心运维平台 - IDCOPS{% endblock %}</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  {% load staticfiles %}
  <link rel="icon" href="{%static 'idcops/favicon.png'%}" sizes="32x32">
  <link rel="icon" href="{%static 'idcops/favicon.png'%}" sizes="192x192">
  <link rel="apple-touch-icon-precomposed" href="{%static 'idcops/favicon.png'%}">
  <meta name="msapplication-TileImage" content="{%static 'idcops/favicon.png'%}">
  <link rel="stylesheet" href="{% static 'idcops/css/bootstrap.min.css'%}">
  <link rel="stylesheet" href="/static/idcops/css/AdminLTE.min.css">
  <link rel="stylesheet" href="{%static 'idcops/css/font-awesome.min.css'%}">
  <!--[if lt IE 9]>
  <script src="/static/idcops/dist/js/html5shiv.min.js"></script>
  <script src="/static/idcops/dist/js/respond.min.js"></script>
  <![endif]-->
</head>
{% block body %}
{% endblock %}
</html>

idcops/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load i18n admin_static %}
{% block title %}登录 数据中心运维平台 - IDCOPS{% endblock %}
{% block body %}
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="{% url 'idcops:index' %}"><b>idcops</b></a>
  </div>
    {% if messages %}
        {% for message in messages %}
        <div id="message" class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible no-margin">
          {{ message }}
        </div>
        {% endfor %}
    {% endif %}
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">登入系统</p>
{% if form.errors and not form.non_field_errors %}
<p class="error">
{% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
</p>
{% endif %}
{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="error">
    {{ error }}
</p>
{% endfor %}
{% endif %}
    <form action="{% url 'idcops:login' %}" method="post">{% csrf_token %} 
      <div class="form-group has-feedback">
        <input type="text" id="id_username" name="username" class="form-control" autocomplete="off" autofocus="autofocus" placeholder="工号">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="text"  onfocus="this.type='password'" id="id_password" name="password" class="form-control" autocomplete="off" placeholder="登录密码">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <input type="hidden" name="next" value="{{ next }}" />
        <!-- /.col -->
    <div class="row">
    <div class="col-xs-8"></div>
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
    <a href="{% url 'idcops:password_reset' %}">{% trans 'Forgotten your password or username?' %}</a>
  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->
</body>
{% endblock %}
</html>

idcops/templates/accounts/logout.html
{% extends "accounts/login.html" %}
{% load i18n admin_static %}
{% block title %}退出登录{% endblock %}

{% block body %}
<body class="hold-transition lockscreen">
<!-- Automatic element centering -->
<div class="lockscreen-wrapper">
  <div class="lockscreen-logo">
    <b>idcops</b>
  </div>
  <!-- User name -->
  <div class="lockscreen-name">idcops</div>
  <!-- START LOCK SCREEN ITEM -->
  <div class="lockscreen-item">
    <!-- lockscreen image -->
    <div class="lockscreen-image">
      <img src="/static/idcops/img/default.png" alt="User Image">
    </div>
    <form class="lockscreen-credentials" action="" method="post">
      <div class="input-group">
        <input type="text" class="form-control" disabled="disabled" autocomplete="off"  placeholder="{%now 'Ymd'%}">

      </div>
    </form>
  </div>
  <div class="text-center">
    <a href="{% url 'idcops:login' %}">{% trans 'Log in again' %}</a>
  </div>
  <div class="lockscreen-footer text-center">
    <p>{% trans "Thanks for spending some quality time with the Web site today." %}</p><br>
    Copyright &copy; 2016 <b>idcops</b><br>
    All rights reserved
  </div>
</div>
<!-- /.center -->
</body>
{% endblock %}

idcops/templates/accounts/password_change_done.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% block userlinks %}{% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %}{% trans 'Change password' %} / <a href="{% url 'idcops:logout' %}">{% trans 'Log out' %}</a>{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'idcops:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password change' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
<p>{% trans 'Your password was changed.' %}</p>
{% endblock %}

<div class="login-box">
  <div class="login-logo">
    <a href="{% url 'idcops:index' %}">{% trans 'Home' %}</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">

    {% if messages %}
        {% for message in messages %}
        <div id="message" class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible no-margin">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
          {{ message }}
        </div>
        {% endfor %}
    {% endif %}

    <p class="login-box-msg">Login ...</p>

{% if form.errors and not form.non_field_errors %}
<p class="error">
{% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="error">
    {{ error }}
</p>
{% endfor %}
{% endif %}

    <form action="" method="post">{% csrf_token %}
      <div class="form-group has-feedback">
        <input type="text" id="id_username" name="username" class="form-control" autocomplete="off" autofocus="autofocus" placeholder="工号">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="text"  onfocus="this.type='password'" id="id_password" name="password" class="form-control" autocomplete="off" placeholder="登录密码">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
        <!-- /.col -->
    <div class="row">
    <div class="col-xs-8"></div>
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
        </div>
        <input type="hidden" name="next" value="{{ next }}" />
        <!-- /.col -->
      </div>
    </form>
    <a href="{% url 'idcops:password_reset' %}">{% trans 'Forgotten your password or username?' %}</a>
  </div>
  <!-- /.login-box-body -->
</div>

idcops/templates/accounts/password_change_form.html
{% extends 'base/edit.html' %}
{% load i18n static app_extras%}
{% block title %}修改密码 数据中心运维平台 - IDCOPS{% endblock %}
{% block content-header %}<h1>修改密码 <small> {{request.user}}</small></h1>{% endblock %}

{% block form %}
<form method="post" class="form-horizontal">{% csrf_token %}
<div class="box-body">
{% if form.errors %}
    <p class="errornote">
    {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
{% endif %}


<p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

<fieldset class="module aligned wide margin-bottom">

<div class="form-row">
    {{ form.old_password.errors }}
    {{ form.old_password.label_tag }} {{ form.old_password|addcss:"form-control" }}
</div>

<div class="form-row">
    {{ form.new_password1.errors }}
    {{ form.new_password1.label_tag }} {{ form.new_password1|addcss:"form-control" }}
    {% if form.new_password1.help_text %}
    <div class="help">{{ form.new_password1.help_text|safe }}</div>
    {% endif %}
</div>

<div class="form-row">
{{ form.new_password2.errors }}
    {{ form.new_password2.label_tag }} {{ form.new_password2|addcss:"form-control" }}
    {% if form.new_password2.help_text %}
    <div class="help">{{ form.new_password2.help_text|safe }}</div>
    {% endif %}
</div>

</fieldset>

<div class="submit-row">
    <input type="submit" value="{% trans 'Change my password' %}" class="btn btn-primary btn-sm" />
</div>

</div>
</form>
{%endblock form%}

idcops/templates/accounts/password_reset_complete.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'idcops:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}

{% block content %}

<p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{% url 'idcops:login' %}">{% trans 'Log in' %}</a></p>

{% endblock %}

idcops/templates/accounts/password_reset_confirm.html
{% extends "accounts/base.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'idcops:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset confirmation' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}

{% if validlink %}

<p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <div class="form-row field-password1">
        {{ form.new_password1.errors }}
        <label for="id_new_password1">{% trans 'New password:' %}</label>
        {{ form.new_password1 }}
    </div>
    <div class="form-row field-password2">
        {{ form.new_password2.errors }}
        <label for="id_new_password2">{% trans 'Confirm password:' %}</label>
        {{ form.new_password2 }}
    </div>
    <input type="submit" value="{% trans 'Change my password' %}" />
</fieldset>
</form>

{% else %}

<p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}

{% endblock %}

idcops/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'idcops:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

idcops/templates/accounts/password_reset_form.html
{% extends 'accounts/base.html' %}
{% load i18n static %}
{% block body %}
<body class="hold-transition lockscreen">
<!-- Automatic element centering -->
<div class="lockscreen-wrapper">
  <div class="lockscreen-logo">
    <b>idcops</b>
  </div>
  <p>{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>
  <!-- User name -->
  <div class="lockscreen-name">{{request.user}}</div>
  <!-- START LOCK SCREEN ITEM -->
  <div class="lockscreen-item">
    <!-- lockscreen image -->
    <div class="lockscreen-image">
      <img src="/static/idcops/img/default.png" alt="User Image">
    </div>
    <form class="lockscreen-credentials" method="post">{% csrf_token %}
        <div class="input-group">
            {{ form.email.errors }}
            <input type="email" class="form-control" autocomplete="off" name="email" maxlength="254" required="" placeholder="{% trans 'Email address' %}" id="id_email">
            <div class="input-group-btn">
              <button type="button" class="btn"><i class="fa fa-arrow-right text-muted"></i></button>
            </div>
        </div>
        <!--input type="submit" value="{% trans 'Reset my password' %}" /-->
    </form>
  </div>
  <div class="text-center">
    <a href="{% url 'idcops:login' %}">{% trans 'Log in again' %}</a>
  </div>
  <div class="lockscreen-footer text-center">
    Copyright &copy; 2016 <b>idcops</b><br>
    All rights reserved
  </div>
</div>
<!-- /.center -->
</body>

{% endblock %}