idcops/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, include, static
from idcops import views
from idcops.list import ListModelView
from idcops.detail import DetailModelView
from idcops.edit import NewModelView, EditModelView

app_name = 'idcops'


accounts_urls = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^profile/', views.ProfileView.as_view(), name='profile'),
    url(r'^password_change/$', views.password_change, name='password_change'),
    url(r'^password_change/done/$', views.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.reset, name='password_reset_confirm'),
    url(r'^reset/done/$', views.reset_done, name='password_reset_complete'),
]


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^list/zonemap/', views.ZonemapView.as_view(), name='zonemap'),
    url(r'^(?:new/(?P<model>\w+))/$', NewModelView.as_view(), name='new'),
    url(r'^(?:list/(?P<model>\w+))/$', ListModelView.as_view(), name='list'),
    url(r'^(?:detail/(?:(?P<model>\w+)-(?P<pk>\d+)))/$', DetailModelView.as_view(), name='detail'),
    url(r'^(?:update/(?:(?P<model>\w+)-(?P<pk>\d+)))/$', EditModelView.as_view(), name='update'),
    url(r'^upload/$', views.SummernoteUploadAttachment.as_view(), name='upload'),
]


if settings.DEBUG:
    urlpatterns += static.static(settings.STATIC_URL,
                                 document_root=settings.STATIC_ROOT)
    urlpatterns += static.static(settings.MEDIA_URL,
                                 document_root=settings.MEDIA_ROOT)

idcops_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import notifications.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('idcops.urls')),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

idcops/lib/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

try:
    import chain
except:
    from itertools import chain

from django.db import models
from django.utils import formats, six, timezone

class ModelDiffMixin(object):
    """
    A model mixin that tracks model fields' values and provide useful API
    to know what fields have been changed.

    The main value is to allow simply changing the values and then saving the
    object only if it is "really changed"
    """
    def __init__(self, *args, **kwargs):
        super(ModelDiffMixin, self).__init__(*args, **kwargs)
        self.__initial = self._dict

    @property
    def diff(self):
        d1 = self.__initial
        d2 = self._dict
        diffs = [(k, (v, d2[k])) for k, v in d1.items() if v != d2[k]]
        return dict(diffs)

    @property
    def has_changed(self):
        return bool(self.diff)

    @property
    def changed_fields(self):
        return list(self.diff.keys())

    @property
    def get_d1(self):
        return self.__initial

    @property
    def get_d2(self):
        return self._dict

    @property
    def changed_field_names(self):
        data = {}
        for field_name in self.changed_fields:
            field = self._meta.get_field(field_name)
            data[field.name] = field.verbose_name
        return data

    @property
    def _dict(self):
        exclude = ['operator_id', 'creator_id', 'created', 'modified']
        opts = self._meta
        data = {}
        keys = [f.attname for f in opts.fields]
        for f in chain(opts.many_to_many):
            #if isinstance(f, models.ManyToManyField):
            if self.pk is None:
                data[f.name] = []
            else:
                data[f.name] = list(f.value_from_object(self).values_list('pk', flat=True))
        original = { k:self.__dict__.get(k) for k in keys if k not in exclude }
        data.update(**original)
        for key, value in data.items():
            if isinstance(value, timezone.datetime):
                value = formats.localize(timezone.template_localtime(value))
            data.update(**{key: value})
        return data

    def get_field_diff(self, field_name):
        """
        Returns a diff for field if it's changed and None otherwise.
        """
        return self.diff.get(field_name, None)

    def save(self, *args, **kwargs):
        """
        Saves model and set initial state.
        """
        super(ModelDiffMixin, self).save(*args, **kwargs)
        self.__initial = self._dict

    class Meta:
        abstract = True


class AbsoluteUrlMixin(object):
    def get_absolute_url(self):
        opts = self._meta
        if opts.proxy:
            opts = opts.concrete_model._meta
        return reverse_lazy(
            'admin:{}_{}_change'.format(
                opts.app_label, opts.model_name
            ), args=(self.pk,)
        )

idcops/lib/models/utils.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import hashlib
import mimetypes
import filetype


def get_file_mimetype(filepath):
    _, ext = os.path.splitext(filepath)
    kind = filetype.guess(filepath)
    if kind:
        mime = kind.mime
        ext = '.' + kind.extension
    else:
        try:
            mime = mimetypes.types_map.get(ext)
        except:
            mime = ext = None
    return (mime, ext)

idcops/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import uuid

from django.db import models
from django.db.models.fields import BLANK_CHOICE_DASH
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import (
    GenericForeignKey, GenericRelation
)

from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import formats, timezone
from django.utils.encoding import python_2_unicode_compatible, force_text
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _
from django.views.generic.base import logger

try:
    from django.core.urlresolvers import reverse_lazy
except:
    from django.urls import reverse_lazy

from django.db.models import options

# Create your models here.
from idcops.lib.models.utils import get_file_mimetype


def upload_to(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    today = timezone.datetime.now().strftime(r'%Y/%m/%d')
    return os.path.join('uploads', today, filename)


EXT_NAMES = (
    'level', 'hidden', 'dashboard', 'metric', 'icon',
    'icon_color', 'default_filters', 'list_display', 'extra_fields'
)

models.options.DEFAULT_NAMES += EXT_NAMES

COLOR_MAPS = (
    ("red", "红色"),
    ("orange", "橙色"),
    ("yellow", "黄色"),
    ("green", "深绿色"),
    ("blue", "蓝色"),
    ("muted", "灰色"),
    ("black", "黑色"),
    ("aqua", "浅绿色"),
    ("gray", "浅灰色"),
    ("navy", "海军蓝"),
    ("teal", "水鸭色"),
    ("olive", "橄榄绿"),
    ("lime", "高亮绿"),
    ("fuchsia", "紫红色"),
    ("purple", "紫色"),
    ("maroon", "褐红色"),
    ("white", "白色"),
    ("light-blue", "暗蓝色"),
)


class Mark(models.Model):
    CHOICES = (
        ('shared', "已共享的"),
        ('pre_share', "预共享的"),
    )
    mark = models.CharField(
        max_length=64, choices=CHOICES,
        blank=True, null=True,
        verbose_name="系统标记", help_text="系统Slug内容标记")

    class Meta:
        level = 0
        hidden = False
        dashboard = False
        metric = ""
        icon = 'fa fa-circle-o'
        icon_color = ''
        default_filters = {'deleted': False}
        list_display = '__all__'
        extra_fields = []
        abstract = True

    @cached_property
    def get_absolute_url(self):
        opts = self._meta
        # if opts.proxy:
        #    opts = opts.concrete_model._meta
        url = reverse_lazy('idcops:detail', args=[opts.model_name, self.pk])
        return url

    @cached_property
    def get_edit_url(self):
        opts = self._meta
        url = reverse_lazy('idcops:update', args=[opts.model_name, self.pk])
        return url

    def title_description(self):
        return self.__str__()


class Creator(models.Model):
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT,
        related_name="%(app_label)s_%(class)s_creator",
        verbose_name="创建人", help_text="该对象的创建人")

    class Meta:
        abstract = True


class Operator(models.Model):
    operator = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
        related_name="%(app_label)s_%(class)s_operator",
        blank=True, null=True,
        verbose_name="修改人", help_text="该对象的修改人"
    )

    class Meta:
        abstract = True


class Created(models.Model):
    created = models.DateTimeField(
        default=timezone.datetime.now, editable=True,
        verbose_name="创建日期", help_text="该对象的创建日期"
    )

    class Meta:
        abstract = True


class Modified(models.Model):
    modified = models.DateTimeField(
        auto_now=True, verbose_name="修改日期",
        help_text="该对象的修改日期"
    )

    class Meta:
        abstract = True
        ordering = ['-modified']


class Actived(models.Model):
    actived = models.NullBooleanField(
        default=True, verbose_name="已启用",
        help_text="该对象是否为有效资源"
    )

    class Meta:
        abstract = True


class Deleted(models.Model):
    deleted = models.NullBooleanField(
        default=False, editable=False,
        verbose_name="已删除", help_text="该对象是否已被删除"
    )

    class Meta:
        abstract = True


class Parent(models.Model):
    parent = models.ForeignKey(
        'self',
        blank=True, null=True, on_delete=models.SET_NULL,
        related_name="%(app_label)s_%(class)s_parent",
        verbose_name="父级对象", help_text="该对象的上一级关联对象"
    )

    class Meta:
        abstract = True


class Onidc(models.Model):
    onidc = models.ForeignKey(
        'Idc',
        blank=True, null=True, on_delete=models.PROTECT,
        related_name="%(app_label)s_%(class)s_onidc",
        verbose_name="所属机房", help_text="该资源所属的机房"
    )

    class Meta:
        abstract = True


class Tag(models.Model):
    tags = models.ManyToManyField(
        'Option',
        blank=True, limit_choices_to={'flag__icontains': 'tags'},
        related_name="%(app_label)s_%(class)s_tags",
        verbose_name="通用标签",
        help_text="可拥有多个标签,字段数据来自机房选项"
    )

    class Meta:
        abstract = True


class ClientAble(models.Model):
    client = models.ForeignKey(
        'Client',
        on_delete=models.PROTECT,
        null=True, blank=True,
        related_name="%(app_label)s_%(class)s_client",
        verbose_name="所属客户",
        help_text="该资源所属的客户信息"
    )

    class Meta:
        abstract = True


class RackAble(models.Model):
    rack = models.ForeignKey(
        'Rack',
        on_delete=models.PROTECT,
        null=True, blank=True,
        related_name="%(app_label)s_%(class)s_rack",
        verbose_name="所属机柜",
        help_text="该资源所属的机柜信息"
    )

    class Meta:
        abstract = True


class Intervaltime(models.Model):
    start_time = models.DateTimeField(
        default=timezone.datetime.now, editable=True,
        verbose_name="开始时间", help_text="该对象限定的开始时间"
    )
    end_time = models.DateTimeField(
        default=timezone.datetime.now, editable=True,
        null=True, blank=True,
        verbose_name="结束时间", help_text="该对象限定的结束时间"
    )

    class Meta:
        abstract = True


class PersonTime(Creator, Created, Operator, Modified):
    class Meta:
        abstract = True


class ActiveDelete(Actived, Deleted):
    class Meta:
        abstract = True


class Contentable(Onidc, Mark, PersonTime, ActiveDelete):
    content_type = models.ForeignKey(
        ContentType,
        models.SET_NULL,
        blank=True,
        null=True,
        verbose_name=_('content type'),
        related_name="%(app_label)s_%(class)s_content_type",
        limit_choices_to={'app_label': 'idcops'}
    )
    object_id = models.PositiveIntegerField(
        _('object id'), blank=True, null=True)
    object_repr = GenericForeignKey('content_type', 'object_id')
    content = models.TextField(verbose_name="详细内容", blank=True)

    def __str__(self):
        return force_text(self.object_repr)

    class Meta:
        abstract = True


class Comment(Contentable):
    class Meta(Mark.Meta):
        hidden = True
        default_permissions = ('view', 'add', 'change', 'delete', 'exports')
        verbose_name = verbose_name_plural = "备注信息"


class Configure(Contentable):
    class Meta(Mark.Meta):
        hidden = True
        default_permissions = ('view', 'add', 'change', 'delete', 'exports')
        verbose_name = verbose_name_plural = "用户配置"

    def __str__(self):
        return "{}-{} : {}".format(self.creator, self.content_type, self.pk)


class Remark(models.Model):
    comment = GenericRelation(
        'Comment',
        related_name="%(app_label)s_%(class)s_comment",
        verbose_name="备注信息")

    @property
    def remarks(self):
        return self.comment.filter(deleted=False, actived=True)

    class Meta:
        abstract = True


class Syslog(Contentable):
    action_flag = models.CharField(_('action flag'), max_length=32)
    message = models.TextField(_('change message'), blank=True)
    object_desc = models.CharField(
        max_length=128,
        verbose_name="对象描述"
    )
    related_client = models.CharField(
        max_length=128,
        blank=True, null=True,
        verbose_name="关系客户"
    )

    def title_description(self):
        time = formats.localize(timezone.template_localtime(self.created))
        text = '{} > {} > {}了 > {}'.format(
            time, self.creator, self.action_flag, self.content_type
        )
        return text

    class Meta(Mark.Meta):
        icon = 'fa fa-history'
        list_display = [
            'created', 'creator', 'action_flag', 'content_type',
            'object_desc', 'related_client', 'message', 'actived',
        ]
        default_permissions = ('view', 'add', 'change', 'delete', 'exports')
        ordering = ['-created', ]
        verbose_name = verbose_name_plural = _('log entries')


@python_2_unicode_compatible
class User(AbstractUser, Onidc, Mark, ActiveDelete, Remark):
    slaveidc = models.ManyToManyField(
        'Idc',
        blank=True,
        verbose_name="附属机房",
        related_name="%(app_label)s_%(class)s_slaveidc"
    )
    upper = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        verbose_name="直属上级",
        related_name="%(app_label)s_%(class)s_upper"
    )
    mobile = models.CharField(max_length=16, blank=True, verbose_name="手机号码")
    avatar = models.ImageField(
        upload_to='avatar/%Y/%m/%d',
        default="avatar/default.png",
        verbose_name="头像"
    )
    settings = models.TextField(
        blank=True,
        verbose_name=_("settings"),
        help_text=_("user settings use json format")
    )

    def __str__(self):
        return self.first_name or self.username

    def title_description(self):
        text = '{} > {} '.format(
            self.onidc, self.__str__()
        )
        return text

idcops/templates/document/detail.html
{% extends 'base/detail.html' %}
{% load app_extras %}
{% block main-content %}
<div class="box box-{%if object.actived%}success{%else%}danger{%endif%}">
  <div class="box-header with-border">
    <h3 class="box-title">{{object}}</h3>
    <div class="box-tools pull-right">
      <button type="button" onclick="window.history.go(-1)" title="返回上一页" class="btn btn-default btn-sm margin-r-5">
        <i class="fa fa-arrow-left"></i><span class="hidden-xs"> 返回</span>
      </button>
      {%if 'idcops.change_'|add:meta.model_name in perms and can_change%}
      <a class="btn btn-primary btn-sm margin-r-5" title="编辑 {{object}}" href="{%url 'idcops:update' meta.model_name object.pk%}">
        <i class="fa fa-edit"></i><span class="hidden-xs"> 编辑</span></a>
      {%endif%}
      <a class="btn btn-default btn-sm" data-toggle="collapse" data-parent="#accordion" href="#remark-info" aria-expanded="true">
        <i class="fa fa-bookmark-o"></i><span class="hidden-xs">{%if object.remarks %} {{object.remarks.count}}条备注{%else%} 新建备注{%endif%}</span></a>
    </div>
  </div>
  <div class="box-body">
  <p>{{object.body|safe}}</p>
  </div>
</div>
{% endblock %}

idcops/templates/document/edit.html
{% extends 'base/base.html' %}
{% load app_extras static%}
{% block title %}编辑 {{meta.title}}{% endblock %}
{% block extra-css %}
{{form.media.css}}
<link rel="stylesheet" href="{% static '/idcops/dist/summernote.css' %}">
{% endblock %}
{% block content-header %}<h1>{{meta.verbose_name}} <small> 编辑{{meta.verbose_name}}</small></h1>{% endblock %}
{% block breadcrumb %}
  <li><a href="{% url 'idcops:index' %}"><i class="fa fa-dashboard"></i> 仪表盘</a></li>
  <li class="active">{{meta.verbose_name}}</li>
{% endblock %}
{% block main-content %}
<div class="box box-warning">
    <div class="box-header with-border">
        <h3 class="box-title"> 编辑{{meta.verbose_name}}</h3>
        <div class="box-tools pull-right">
          {%if 'mark' in form.fields%}
          <button type="button" data-complete-text="已共享" data-toggle="buttons" id="to_shared" class="btn btn-info btn-sm hidden-xs">共享</button>
          {%endif%}
        </div>
    </div>
    <div class="box-body">
        <form action="" method="POST" class="form" id="{{meta.model_name}}-edit">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
          {{ hidden }}
        {% endfor %}
        <div class="box-body">
        {% for field in form.visible_fields %}
        <div class="form-group">
        <label class="control-label">{{ field.label }}:</label>
          {{field}}
        <div class="help-block">
        {{ field.help_text|safe}}
          <div class="text-red">{{ field.errors}}</div>
        </div>
        </div>
        {% endfor %}
        </div>
        <div class="box-footer">
        <button type="button" class="btn btn-default btn-sm margin-r-5" onclick="window.history.go(-1)">取消并返回</button>
        <div class="btn-group pull-right">
        <button type="submit" name="_addanother" class="btn btn-info btn-sm margin-r-5">保存并新增</button>
        <button type="submit" name="_save" class="btn btn-info btn-sm">提交</button>
        </div>
        </div>
        </form>
    </div>
</div>
{% endblock %}
{% block extra-js %}
{{form.media.js}}
<script src="{%static 'idcops/dist/summernote.js'%}"></script>
<script src="{%static 'idcops/dist/lang/summernote-zh-CN.min.js'%}"></script>
<script>
$(document).ready(function (){
// reset modal cache
$('body').on('hidden.bs.modal', '.modal', function () {
    $(this).removeData('bs.modal');
});
    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie != '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
              var cookie = jQuery.trim(cookies[i]);
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) == (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
    };

    // summernote.image.upload
    function sendFile(file, el) {
      var form_data = new FormData();
      //var csrftoken = getCookie('csrftoken');
      var csrfmiddlewaretoken = $('form input[name="csrfmiddlewaretoken"]').val()
      //form_data.append('csrftoken', csrftoken);
      form_data.append("csrfmiddlewaretoken", csrfmiddlewaretoken);
      form_data.append('files', file);
      $.ajax({
          data: form_data,
          type: "POST",
          url: "{%url 'idcops:upload' %}",
          cache: false,
          contentType: false,
          processData: false,
          success: function (data) {
            $.each(data.files, function (index, file) {
              $(el).summernote("insertImage", file.url);
            });
          }
      });
    }

    $('#id_body').summernote({
      height: 500,
      tabsize: 2,
      lang: 'zh-CN',
      popover: {
        image: [],
        link: [],
        air: []
        },
      callbacks: {
        onImageUpload : function(files, editor, welEditable) {
          for(var i = files.length - 1; i >= 0; i--) {
            sendFile(files[i], this);
          }
        }
      }
    });

// Select2
$("select").select2({language: "zh-CN"});

$(function() {
    $("#to_shared").click(function(){
        $(this).button('loading').delay(300).queue(function() {
          $("#id_mark").val('shared');
          $(this).button('complete');
          $(this).removeClass('btn-info').addClass('btn-success');
          $(this).button('reset').delay(300).dequeue();
        });
    });
});

var oldFormData = $('form').serialize();
$("form").submit(function(){
  var newFormData = $('form').serialize();
  if (oldFormData == newFormData){
    alert("没有任何改变,已经阻止表单提交.");
    return false;
  }
});

//DateTimeField
var DateTimeField = $("input[data-datetime='true']");
if (DateTimeField.length != 0) {
  DateTimeField.daterangepicker({
    timePicker: true,
    timePickerIncrement: 5,
    timePicker24Hour: true,
    locale:{
      format: 'YYYY-MM-DD H:mm:ss',
      applyLabel: '确认',
      cancelLabel: '取消',
      fromLabel: '从',
      toLabel: '到',
      weekLabel: 'W',
      customRangeLabel: '选择时间',
      daysOfWeek:["日","一","二","三","四","五","六"],
      monthNames: ["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"],
    },
    singleDatePicker: true
  });
}

});
</script>
{% endblock %}

idcops/templates/document/new.html
{% extends 'base/new.html' %}
{% load static app_extras %}
{% block extra-css %}
{{form.media.css}}
{% endblock %}

{%block form%}
<form action="" method="POST" role="form" class="form" id="{{meta.model_name}}-new">
  <div class="box-body">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
    <div class="form-group">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>{{ field }}
      <div class="help-block">
        {%if field.field.required%}<span class="text-red">必填 </span>{%endif%}
          {{ field.help_text|safe}}
          <div class="text-red">{{ field.errors|safe }}</div>
      </div>
    </div>
    {% endfor %}
    </div>
    <div class="box-footer">
      <button type="button" class="btn btn-default btn-sm" onclick="window.history.go(-1)">取消并返回</button>
      <div class="pull-right">
        <button type="submit" name="_saverlist" class="btn btn-primary btn-sm margin-r-5">保存</button>
        <button type="submit" name="_addanother" class="btn btn-primary btn-sm margin-r-5">保存并新增</button>
        <button type="submit" name="_saverview" class="btn btn-primary btn-sm">保存并查看</button>
      </div>
    </div>
  </div>
</form>
{% endblock %}

{% block extra-js %}
{{form.media.js}}

<script type="text/javascript">
  $(document).ready(function() {
    
    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie != '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
              var cookie = jQuery.trim(cookies[i]);
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) == (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
    };

    // summernote.image.upload
    function sendFile(file, el) {
      var form_data = new FormData();
      //var csrftoken = getCookie('csrftoken');
      var csrfmiddlewaretoken = $('form input[name="csrfmiddlewaretoken"]').val()
      //form_data.append('csrftoken', csrftoken);
      form_data.append("csrfmiddlewaretoken", csrfmiddlewaretoken);
      form_data.append('files', file);
      $.ajax({
          data: form_data,
          type: "POST",
          url: "{%url 'idcops:upload' %}",
          cache: false,
          contentType: false,
          processData: false,
          success: function (data) {
            $.each(data.files, function (index, file) {
              $(el).summernote("insertImage", file.url);
            });
          }
      });
    }

    $('#id_body').summernote({
      height: 500,
      tabsize: 2,
      lang: 'zh-CN',
      popover: {
        image: [],
        link: [],
        air: []
        },
      callbacks: {
        onImageUpload : function(files, editor, welEditable) {
          for(var i = files.length - 1; i >= 0; i--) {
            sendFile(files[i], this);
          }
        }
      }
    });

    // reset modal cache
    $('body').on('hidden.bs.modal', '.modal', function () {
        $(this).removeData('bs.modal');
    });
    // Select2
    $("select").select2({language: "zh-CN"});
    $(function() {
        $("#to_shared").click(function(){
            $(this).button('loading').delay(300).queue(function() {
              $("#id_mark").val('shared');
              $(this).button('complete');
              $(this).removeClass('btn-info').addClass('btn-success');
              $(this).button('reset').delay(300).dequeue();
            });
        });
    });
    var formSubmitted = false;
    var oldFormData = $('form').serialize();
    $("form").submit(function(e){
      var newFormData = $('form').serialize();
      if (oldFormData == newFormData){
        alert("没有任何改变,已经阻止表单提交.");
        return false;
      }
      formSubmitted = true;
    });
  });
</script>
{% endblock %}