idcops/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, include, static
from idcops import views
from idcops.list import ListModelView
from idcops.detail import DetailModelView
from idcops.edit import NewModelView, EditModelView

app_name = 'idcops'


accounts_urls = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^profile/', views.ProfileView.as_view(), name='profile'),
    url(r'^password_change/$', views.password_change, name='password_change'),
    url(r'^password_change/done/$', views.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.reset, name='password_reset_confirm'),
    url(r'^reset/done/$', views.reset_done, name='password_reset_complete'),
]


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^list/zonemap/', views.ZonemapView.as_view(), name='zonemap'),
    url(r'^(?:new/(?P<model>\w+))/$', NewModelView.as_view(), name='new'),
    url(r'^(?:list/(?P<model>\w+))/$', ListModelView.as_view(), name='list'),
    url(r'^(?:detail/(?:(?P<model>\w+)-(?P<pk>\d+)))/$', DetailModelView.as_view(), name='detail'),
    url(r'^(?:update/(?:(?P<model>\w+)-(?P<pk>\d+)))/$', EditModelView.as_view(), name='update'),
    url(r'^upload/$', views.SummernoteUploadAttachment.as_view(), name='upload'),
]


if settings.DEBUG:
    urlpatterns += static.static(settings.STATIC_URL,
                                 document_root=settings.STATIC_ROOT)
    urlpatterns += static.static(settings.MEDIA_URL,
                                 document_root=settings.MEDIA_ROOT)

idcops_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import notifications.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('idcops.urls')),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

idcops/lib/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

try:
    import chain
except:
    from itertools import chain

from django.db import models
from django.utils import formats, six, timezone

class ModelDiffMixin(object):
    """
    A model mixin that tracks model fields' values and provide useful API
    to know what fields have been changed.

    The main value is to allow simply changing the values and then saving the
    object only if it is "really changed"
    """
    def __init__(self, *args, **kwargs):
        super(ModelDiffMixin, self).__init__(*args, **kwargs)
        self.__initial = self._dict

    @property
    def diff(self):
        d1 = self.__initial
        d2 = self._dict
        diffs = [(k, (v, d2[k])) for k, v in d1.items() if v != d2[k]]
        return dict(diffs)

    @property
    def has_changed(self):
        return bool(self.diff)

    @property
    def changed_fields(self):
        return list(self.diff.keys())

    @property
    def get_d1(self):
        return self.__initial

    @property
    def get_d2(self):
        return self._dict

    @property
    def changed_field_names(self):
        data = {}
        for field_name in self.changed_fields:
            field = self._meta.get_field(field_name)
            data[field.name] = field.verbose_name
        return data

    @property
    def _dict(self):
        exclude = ['operator_id', 'creator_id', 'created', 'modified']
        opts = self._meta
        data = {}
        keys = [f.attname for f in opts.fields]
        for f in chain(opts.many_to_many):
            #if isinstance(f, models.ManyToManyField):
            if self.pk is None:
                data[f.name] = []
            else:
                data[f.name] = list(f.value_from_object(self).values_list('pk', flat=True))
        original = { k:self.__dict__.get(k) for k in keys if k not in exclude }
        data.update(**original)
        for key, value in data.items():
            if isinstance(value, timezone.datetime):
                value = formats.localize(timezone.template_localtime(value))
            data.update(**{key: value})
        return data

    def get_field_diff(self, field_name):
        """
        Returns a diff for field if it's changed and None otherwise.
        """
        return self.diff.get(field_name, None)

    def save(self, *args, **kwargs):
        """
        Saves model and set initial state.
        """
        super(ModelDiffMixin, self).save(*args, **kwargs)
        self.__initial = self._dict

    class Meta:
        abstract = True


class AbsoluteUrlMixin(object):
    def get_absolute_url(self):
        opts = self._meta
        if opts.proxy:
            opts = opts.concrete_model._meta
        return reverse_lazy(
            'admin:{}_{}_change'.format(
                opts.app_label, opts.model_name
            ), args=(self.pk,)
        )

idcops/lib/models/utils.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import hashlib
import mimetypes
import filetype


def get_file_mimetype(filepath):
    _, ext = os.path.splitext(filepath)
    kind = filetype.guess(filepath)
    if kind:
        mime = kind.mime
        ext = '.' + kind.extension
    else:
        try:
            mime = mimetypes.types_map.get(ext)
        except:
            mime = ext = None
    return (mime, ext)

idcops/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Create your views here.
from django.apps import apps
from django.views.generic import View, TemplateView
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView, PasswordChangeDoneView,
    PasswordChangeView
)
from django.template.loader import render_to_string
from django.utils.translation import ugettext as _
from django.utils.encoding import force_text
from django.utils.functional import cached_property

try:
    from django.core.urlresolvers import reverse_lazy
except:
    from django.urls import reverse_lazy

from idcops.lib.utils import shared_queryset
from idcops.mixins import BaseRequiredMixin
from idcops.models import (
    Option, Rack, Device, Online, Syslog, ContentType, Zonemap, Client
)
from idcops.forms import ZonemapNewForm


login = LoginView.as_view(template_name='accounts/login.html')

logout = LogoutView.as_view(template_name='accounts/logout.html')

password_reset = PasswordResetView.as_view(
    template_name='accounts/password_reset_form.html',
    email_template_name='accounts/password_reset_email.html',
    subject_template_name='accounts/password_reset_subject.txt',
)

password_reset_done = PasswordResetDoneView.as_view(
    template_name='accounts/password_reset_done.html'
)

reset = PasswordResetConfirmView.as_view(
    template_name='accounts/password_reset_confirm.html'
)

reset_done = PasswordResetCompleteView.as_view(
    template_name='accounts/password_reset_complete.html'
)


class PasswordChangeView(BaseRequiredMixin, PasswordChangeView):
    template_name = 'accounts/password_change_form.html'
    success_url = reverse_lazy('idcops:index')


password_change = PasswordChangeView.as_view()

password_change_done = PasswordChangeDoneView.as_view(
    template_name='accounts/password_change_done.html'
)


class SummernoteUploadAttachment(BaseRequiredMixin, View):
    def __init__(self):
        super(SummernoteUploadAttachment, self).__init__()

    def get(self, request, *args, **kwargs):
        return JsonResponse({
            'status': 'false',
            'message': _('Only POST method is allowed'),
        }, status=400)

    def post(self, request, *args, **kwargs):
        if not request.FILES.getlist('files'):
            return JsonResponse({
                'status': 'false',
                'message': _('No files were requested'),
            }, status=400)

        # remove unnecessary CSRF token, if found
        kwargs = request.POST.copy()
        kwargs.pop("csrfmiddlewaretoken", None)

        try:
            attachments = []

            for file in request.FILES.getlist('files'):

                # create instance of appropriate attachment class
                from idcops.models import Attachment
                attachment = Attachment()

                attachment.onidc = request.user.onidc
                attachment.creator = request.user
                attachment.file = file
                attachment.name = file.name

                if file.size > 1024 * 1024 * 10:
                    return JsonResponse({
                        'status': 'false',
                        'message': _('File size exceeds the limit allowed and cannot be saved'),
                    }, status=400)

                # calling save method with attachment parameters as kwargs
                attachment.save(**kwargs)
                attachments.append(attachment)

            return HttpResponse(render_to_string('document/upload_attachment.json', {
                'attachments': attachments,
            }), content_type='application/json')
        except IOError:
            return JsonResponse({
                'status': 'false',
                'message': _('Failed to save attachment'),
            }, status=500)


class IndexView(BaseRequiredMixin, TemplateView):

    template_name = 'index.html'

    def make_years(self, queryset):
        years = queryset.datetimes('created', 'month')
        if years.count() > 12:
            ranges = years[(years.count()-12):years.count()]
        else:
            ranges = years[:12]
        return ranges

    def make_device_dynamic_change(self):
        content_type = ContentType.objects.get_for_model(Device)
        logs = Syslog.objects.filter(
            onidc_id=self.onidc_id, content_type=content_type)
        data = {}
        data['categories'] = [m.strftime("%Y-%m")
                              for m in self.make_years(logs)]
        data['moveup'] = []
        data['moving'] = []
        data['movedown'] = []
        for y in self.make_years(logs):
            nlogs = logs.filter(created__year=y.year, created__month=y.month)
            moving = nlogs.filter(
                message__contains='"units"', action_flag="修改").exclude(
                content__contains='"units": [[]').count()
            data['moving'].append(moving)
            moveup = nlogs.filter(action_flag="新增").count()
            data['moveup'].append(moveup)
            cancel_movedown = nlogs.filter(action_flag="取消下架").count()
            movedown = nlogs.filter(action_flag="下架").count()
            data['movedown'].append(movedown-cancel_movedown)
        return data

    def make_rack_dynamic_change(self):
        content_type = ContentType.objects.get_for_model(Rack)
        logs = Syslog.objects.filter(
            onidc_id=self.onidc_id, content_type=content_type)
        data = {}
        data['categories'] = [m.strftime("%Y-%m")
                              for m in self.make_years(logs)]
        data['renew'] = []
        data['release'] = []
        for y in self.make_years(logs):
            nlogs = logs.filter(created__year=y.year, created__month=y.month)
            data['renew'].append(nlogs.filter(action_flag="分配机柜").count())
            data['release'].append(nlogs.filter(action_flag="释放机柜").count())
        return data

    def make_rack_statistics(self):
        data = []
        robjects = Rack.objects.filter(onidc_id=self.onidc_id, actived=True)
        keys = Option.objects.filter(
            flag__in=['Rack-Style', 'Rack-Status'],
            actived=True)
        keys = shared_queryset(keys, self.onidc_id)
        for k in keys:
            d = []
            query = {
                k.flag.split('-')[1].lower(): k
            }
            c = robjects.filter(**query).count()
            if c > 0:
                d.append(force_text(k))
                d.append(c)
            if d:
                data.append(d)
        return data

    def make_online_statistics(self):
        data = []
        dobjects = Online.objects.filter(onidc_id=self.onidc_id)
        keys = Option.objects.filter(flag__in=['Device-Style', 'Device-Tags'])
        keys = shared_queryset(keys, self.onidc_id)
        for k in keys:
            d = []
            if k.flag == 'Device-Style':
                c = dobjects.filter(style=k).count()
            else:
                c = dobjects.filter(tags__in=[k]).count()
            if c > 0:
                d.append(force_text(k))
                d.append(c)
            if d:
                data.append(d)
        return data

    def make_state_items(self):
        state_items = [
            {
                'model_name': app._meta.model_name,
                'verbose_name': app._meta.verbose_name,
                'icon': app._meta.icon,
                'icon_color': 'bg-' + app._meta.icon_color,
                'level': app._meta.level,
                'metric': app._meta.metric,
                'count': app.objects.filter(
                    onidc=self.request.user.onidc).filter(
                    **app._meta.default_filters).count(),
            } for app in apps.get_app_config('idcops').get_models() if getattr(
                app._meta,
                'dashboard')]
        return state_items

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['state_items'] = self.make_state_items()
        context['online_statistics'] = self.make_online_statistics()
        context['device_dynamic_change'] = self.make_device_dynamic_change()
        context['rack_statistics'] = self.make_rack_statistics()
        context['rack_dynamic_change'] = self.make_rack_dynamic_change()
        return context


class ProfileView(BaseRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

    # def get(self, *args, **kwargs):
        # messages.success(self.request, "accounts/profile.html")
        # return super(ProfileView, self).get(*args, **kwargs)


class ZonemapView(BaseRequiredMixin, TemplateView):

    template_name = 'zonemap/detail.html'

    @cached_property
    def get_options(self):
        options = Option.objects.filter(actived=True)
        return shared_queryset(options, self.onidc_id)

    @cached_property
    def get_zones(self):
        return self.get_options.filter(flag='Rack-Zone')

    @cached_property
    def get_zone(self):
        ''' get current zone return zone instance'''
        zone_id = self.request.GET.get('zone_id', None)
        try:
            zone = self.get_zones.get(pk=int(zone_id))
        except BaseException:
            if self.get_zones.filter(master=True).exists():
                zone = self.get_zones.filter(master=True).first()
            else:
                zone = None
        return zone

    def get_mode(self):
        action = self.request.GET.get('action', 'show')
        return action

    def get_racks(self):
        if self.get_zone:
            return Rack.objects.filter(zone_id=self.get_zone)
        return None

    def get_rack_statistics(self):
        data = []
        keys = self.get_options.filter(flag__in=['Rack-Style', 'Rack-Status'])
        ''' id, color, text, flag, description, count '''

idcops/templates/rack/detail.html
{% extends 'base/detail.html' %}
{% load app_extras %}
{%block box-tools-extra%}
{% if object.actived %}
<div class="btn-group margin-r-5">
  {%if 'idcops.add_online' in perms %}
  <a class="btn btn-default btn-sm" href="/new/online/?rack_id={{object.pk}}">
    <i class="fa fa-server"></i><span class="hidden-xs"> 新建设备</span>
  </a>
  {%endif%}

  {%if 'idcops.add_rextend' in perms%}
  <a class="btn btn-default btn-sm" href="{%url 'idcops:new' 'rextend'%}?rack_id={{object.pk}}" data-toggle="modal" data-target="#modal-lg-static">
    <i class="fa fa-battery-2"></i><span class="hidden-xs"> 更新电量</span>
  </a>
  {%endif%}
</div>
{% endif %}
{%endblock box-tools-extra%}
{% block page-extra %}
{% rack_overview object.id '' %}
{% endblock %}

idcops/templates/rack/distribution.html
{% extends 'base/base.html' %}
{% load i18n l10n admin_urls static %}
{% load app_extras static %}
{% block extra-css %}
<link href="/static/idcops/css/select2.min.css" type="text/css" media="all" rel="stylesheet">
{% endblock extra-css %}

{% block content-header %}
<h1>{{meta.verbose_name}}
<small>
  <b class="text-red"> {{queryset.count}} </b>单, 共有<b class="text-red"> {{total.amount__sum}} </b>件物品
</small>
</h1>
{% endblock %}
{% block main-content %}

{% block form %}
<form method="post" class="form">
  {% csrf_token %}
<div class="box box-warning">
  <div class="box-header with-border">
    <h3 class="box-title">请您确认{{action_name}}清单</h3>
    <div class="box-tools pull-right">
      <input type="hidden" name="action" value="{{action}}" />
      <input type="hidden" name="post" value="yes" />
      <input type="submit" class="btn btn-danger btn-sm margin-r-5" value="确定{{action_name}}" />
      <a href="{%url 'idcops:list' meta.model_name%}" class="btn btn-default btn-sm">
        <span>返回列表</span>
      </a>
    </div>
  </div>
  <div class="box-body table-responsive margin-bottom">
  <table id="item-list" class="table table-bordered table-condensed">
    <thead>
      <tr class="active">
        <th width="3%"> #</th>
        <th>机柜名称</th>
        <th>机柜别名</th>
        <th>所在区域</th>
        <th width="30%">分配客户</th>
        <th width="10%">合同电力 (A)</th>
        <th width="13%">机柜状态</th>
        <th width="13%">机柜类型</th>
      </tr>
    </thead>
    <tbody>
      {% for obj in queryset %}
      <input type="hidden" name="index" value="{{ obj.pk|unlocalize }}" />
      <input type="hidden" name="items" value="{{obj.pk}}" />
      <tr class="{% cycle '' 'active' %}">
        <td style="vertical-align:middle;">{{forloop.counter}}.</td>
        <td style="vertical-align:middle;">
          <a data-toggle="modal" data-target="#modal-lg" href="{{obj.get_absolute_url}}">{{obj}}</a>
        </td>
        <td style="vertical-align:middle;">{{obj.cname}}</td>
        <td style="vertical-align:middle;">{{obj.zone}}</td>
        <td class="clearfix" style="vertical-align:middle;">
          <select name="client-{{obj.pk}}" class="form-control">
            <option value="">请选择一个客户</option>
            {%for client in clients%}
            <option value="{{client.id}}">{{client}}</option>
            {%endfor%}
          </select>
        </td>

        <td style="vertical-align:middle;">
          <input id="cpower-{{obj.pk}}" required="required" class="form-control" type="number" name="cpower-{{obj.pk}}" value="10" />
        </td>

        <td class="clearfix" style="vertical-align:middle;">
          <select name="status-{{obj.pk}}" class="form-control">
            {%for s in status%}
            <option value="{{s.id}}">{{s}}</option>
            {%endfor%}
          </select>
        </td>

        <td class="clearfix" style="vertical-align:middle;">
          <select name="style-{{obj.pk}}" class="form-control">
            {%for style in styles%}
            <option value="{{style.id}}">{{style}}</option>
            {%endfor%}
          </select>
        </td>
      </tr>
      {%endfor%}
    </tbody>
  </table>
  </div>

  <div class="box-footer">
    <div class="box-tools pull-right">
      <b>合计：</b><span id="total"></span> 件
    </div>
  </div>
</div>
</form>
{% endblock form %}
{% endblock main-content %}

{% block extra-js%}
<script type="text/javascript" src="/static/idcops/js/select2.min.js"></script>
<script type="text/javascript" src="/static/idcops/js/i18n/zh-CN.js"></script>
<script>
$(document).ready(function (){

// reset modal cache
$('body').on('hidden.bs.modal', '.modal', function () {
    $(this).removeData('bs.modal');
});


function update_total(){
  var inputs = document.querySelectorAll('input[name^="count-"]');
  var total = 0;
  [].forEach.call(inputs, function(input){
    total = total + parseInt(input.value);
  });
  return total
}

var Input = $('input[type="number"]');
if (Input.length != 0){
  $('input[type="number"]').change(function() {
    $("#total").html(update_total());
  });
}

// Select2
var Select = $("select");
if (Select.length != 0) {
  $("select").select2({language: "zh-CN"});
	$("select").on("change", function(){
    var scount = $(this).children("option:selected").length;
    var flag = $(this).attr('name').split('-')[1];
    $('#count-'+flag).val(scount);
    $("#total").html(update_total());
  });
}

});

</script>
{% endblock extra-js%}

idcops/templates/rack/overview.html
<table id="rack-detail" style="margin:0; padding:0;" class="table table-bordered text-center nowarp table-condensed">
  <thead>
    <tr class="active">
        <th style="width:2%">U</th>
        <th style="width:16%">设备编号</th>
        <th>PDU</th>
        <th>设备SN号</th>
        <th>IP地址</th>
        <th>设备型号</th>
        <th>客户名称</th>
        <th class="no-print">操作</th>
    </tr>
  </thead>
  <tbody>
      {% for u in units %}
      {% if not u.actived %}
        <tr name="hasdevice" {%if u in obj_units%}class="danger"{%else%}class="success"{%endif%}>
          {%with ucount=u.online.units.all%}
          <td style="vertical-align: middle;" class="no-padding">{{u}}</td>
          {%if not u.repeat%}
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">
            <a href="{%url 'idcops:detail' 'online' u.online.pk %}">{{u.online.name}}</a>
          </td>
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">
            {%if u.online.pdus%}
              {%for pdu in u.online.pdus.all %}
                <span>{{pdu}} </span>
              {%endfor%}
            {%else%}
              <span>未录入 </span>
            {%endif%}
          </td>
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">
            {%if u.online.sn|first == '_' %}<span>无法查看</span>{%else%}<span>{{ u.online.sn|upper }}</span>{%endif%}
          </td>
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">{{u.online.ipaddr}}</td>
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">{{u.online.model}}</td>
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">{{u.online.client}}</td>
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding no-print">
          <a href="{%url 'idcops:update' 'online' u.online.pk %}">修改</a>
          </td>
          {%endif%}
          {%endwith%}
        </tr>
      {% else %}
        <tr name="nonedevice">
          <td class="no-padding">{{u}}</td>
          <td class="no-padding"></td>
          <td class="no-padding"></td>
          <td class="no-padding"></td>
          <td class="no-padding"></td>
          <td class="no-padding"></td>
          <td class="no-padding"></td>
          <td class="no-padding no-print"></td>
        </tr>
      {% endif %}
      {% endfor %}
  </tbody>
</table>